# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e364ac045a9b82f6205967608b8425b474935500ee0c0a5cb7c8d404dc7568b00549d9da9e28c2cae198e006890b0cb6aaa5b892e1ddd89c7744f4a1744a855e

test:
  secret_key_base: fe53d6394f9e197e963f79ede3ab018fe59712c7782f7fe4cc09375c32c71a694768f68cbe4c8815e06ffd79f00fdc05eb1a78d3b2ceb769b517f6b17c5ec383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
